services:
  db:
        image: mysql:8.0
        ports:
          - 3306:3306
        cap_add:
          - SYS_NICE
        volumes:
          - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        restart: on-failure
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: cloudcomputing2023/bot
    restart: on-failure